.gitignore
Vagrantfile
requirements.txt

Merge branch vagrantfile and requirement.txt

Vagrant file

---

app/__init__.py
app/models.py
app/service.py
setup.cfg
tests/test_models.py
tests/test_service.py

close #9. Configured test environment to run nosetests.

Configured test environment

---

app/__init__.py
app/models.py
app/service.py
run.py
tests/test_models.py
tests/test_service.py

close #18 , implemented required helper functions

Helper functions

---

app/models.py
app/service.py
tests/test_service.py

implemented get reorder list api call

---

Vagrantfile

updated vagrant file

---

Vagrantfile

Close #51. Updated Vagrantfile to provision CouchDB.

Update vagrantfile db

---

app/models.py
app/service.py
tests/test_models.py
tests/test_service.py

Persist model

---

requirements.txt

added flask-restplus to requirement.txt file

---

app/models.py
app/service.py
tests/test_models.py
tests/test_service.py

close #69. Reorder action implemented

Reorder list

---

app/service.py
tests/test_service.py

Close issue #74 

---

app/service.py
tests/test_service.py

List inventory plus

---

app/service.py

Finish create inventory plus

---

app/service.py

Finish delete inventory plus

---

app/service.py

finished update inventory plus

---

app/service.py
tests/test_models.py
tests/test_service.py

Updated get_inventory to restplus Issue #74

Updated get_inventory to restplus

---

manifest.yml

refactored manifest

---

features/inventory.feature
features/steps/inventory_steps.py
run.py

updated testing-server-behave based on restructrued code

---

features/inventory.feature
service/static/index.html
service/static/js/rest_api.js

finished list-inventory-bdd

---

features/inventory.feature

Finish delete inventory bdd

---

features/inventory.feature
features/steps/inventory_steps.py
service/static/js/rest_api.js

finished update-inventory-bdd

---

features/inventory.feature
service/static/index.html
service/static/js/rest_api.js

query inventory

---

features/inventory.feature
service/models.py
service/static/index.html
service/static/js/rest_api.js

Reorder test bdd

---

service/models.py

updated separate db for dev & prod

---

features/inventory.feature
service/__init__.py
service/models.py
service/resources/inventory_collection.py
service/resources/inventory_resource.py
service/resources/reorder_all_action.py
service/resources/reorder_one_action.py
tests/test_service.py

Json error
